# Generated by Django 5.2.7 on 2025-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot_app", "0003_tokenusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenusage",
            name="notified_limit",
            field=models.BooleanField(default=False),
        ),
    ]
